In [2]:
import numpy as np

In [4]:
a = np.array([1,3,5])
a

array([1, 3, 5])

In [5]:
print(a.ndim)

1


In [6]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(b.ndim)

2


In [8]:
b.shape

(2, 3)

# Shaping Arrays

In [12]:
d = np.zeros([2,3], dtype='int64')
d

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [10]:
e = np.ones([3,3])
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
f = np.random.rand(5,3)
f

array([[0.60976638, 0.46181509, 0.22663339],
       [0.47050089, 0.9995801 , 0.10957654],
       [0.10758441, 0.38930373, 0.18568911],
       [0.22678379, 0.44844036, 0.44560244],
       [0.70865882, 0.7156084 , 0.28262067]])

In [13]:
f = np.full((2,2), 10)
f

array([[10, 10],
       [10, 10]])

In [14]:
f = np.full((2,2,3), [4,2,3])
f

array([[[4, 2, 3],
        [4, 2, 3]],

       [[4, 2, 3],
        [4, 2, 3]]])

# Sequence of Integers, Sequence of Floats

In [16]:
g = np.arange(10,50,2)
g

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [18]:
h = np.linspace(10,50,15)
h

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# Element-wise Operations

In [19]:
a = np.array([1,4,6,8])

b = np.array([1,1,1,1])

In [20]:
a

array([1, 4, 6, 8])

In [21]:
b

array([1, 1, 1, 1])

In [22]:
c = a - b

In [23]:
c

array([0, 3, 5, 7])

In [24]:
d = a * b

In [25]:
d

array([1, 4, 6, 8])

In [28]:
fahrenheit = np.array([0, -5, -10])

celcius = (fahrenheit - 31) * (5/9)
celcius

array([-17.22222222, -20.        , -22.77777778])

In [31]:
celcius >= -20 

array([ True,  True, False])

# arange function with reshape function

In [32]:
twod = np.arange(1,16,1).reshape(3,5)
twod

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
twod = np.arange(6,58,3).reshape(3,6)
twod

array([[ 6,  9, 12, 15, 18, 21],
       [24, 27, 30, 33, 36, 39],
       [42, 45, 48, 51, 54, 57]])

# Numpy Indexing

In [34]:
a = np.array([1,3,5,7])
a

array([1, 3, 5, 7])

In [35]:
a[1]

3

In [36]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b[0][0]

1

In [38]:
b[1][1]

5

In [39]:
np.array([b[0,0], b[1,1]])

array([1, 5])

In [40]:
print(b > 5)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [41]:
print(b [b > 5])

[6 7 8 9]


# Numpy Slicing

In [42]:
a = np.array([1,2,5,7,8])
a

array([1, 2, 5, 7, 8])

In [43]:
a[:2]

array([1, 2])

In [44]:
a[0:2]

array([1, 2])

In [45]:
a[2:4]

array([5, 7])

In [46]:
a = np.array([[1,2,5], [6,8,10], [14,17,22]])
a

array([[ 1,  2,  5],
       [ 6,  8, 10],
       [14, 17, 22]])

In [47]:
a[:2]

array([[ 1,  2,  5],
       [ 6,  8, 10]])

In [48]:
a[1:2, 1:3]

array([[ 8, 10]])

# Indexing and Slicing with Breast Cancer Wisconsin Dataset

In [54]:
breastcancer_diag = np.genfromtxt('bcwisconsin.csv', delimiter=',', skip_header=1)
breastcancer_diag 

OSError: bcwisconsin.csv not found.

In [55]:
breastcancer_diag[:, 0:4]

NameError: name 'breastcancer_diag' is not defined